### ISSUE TITLE
Random Micro Stutters every few floors

### ISSUE THREAD

**Issue by AngryMustache** [Speshkitty/DalamudPlugins#3]
Hello,

Really like this trap location helper, but only problem I have with it so far is every few floors or so there will be a micro stutter where the entire game freezes for about a second or so, even when in combat. I was wondering if it's possible that if it's requiring a connection for trap info that it's causing a spike so often? Would it be possible to minimize this from happening, or only when not engaged with an enemy?

It doesn't happen when the plugin isn't enabled, and I have no more information to give since I see nothing in the log files regarding it.

Cheers

edit: new dalamud/ffxiv version broke it so it no longer loads

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Void Dalamud.Game.Gui.ChatGui.Enable()'.
   at PotDHelper.Plugin..ctor(DalamudPluginInterface pluginInterface)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 414`

**Comment by Speshkitty** [comment]
Fixed as of v1.4.0.0
